<?php
$data = array (
  26 => 
  array (
    'cat_id' => '26',
    'cat_name' => '娱乐',
    'measure_unit' => '本',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '5',
    'category_img' => NULL,
    'goods_num' => 0,
    'level' => 0,
    'id' => '26',
    'name' => '娱乐',
  ),
  39 => 
  array (
    'cat_id' => '39',
    'cat_name' => '幽默与趣味',
    'measure_unit' => '本',
    'parent_id' => '26',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'category_img' => 'images/201607/1467420446680948258.jpg',
    'goods_num' => 0,
    'level' => 1,
    'id' => '39',
    'name' => '幽默与趣味',
  ),
  38 => 
  array (
    'cat_id' => '38',
    'cat_name' => '星座血型',
    'measure_unit' => '本',
    'parent_id' => '26',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'category_img' => 'images/201607/1467420466043143633.jpg',
    'goods_num' => '8',
    'level' => 1,
    'id' => '38',
    'name' => '星座血型',
  ),
  37 => 
  array (
    'cat_id' => '37',
    'cat_name' => '手工DIY',
    'measure_unit' => '本',
    'parent_id' => '26',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'category_img' => 'images/201607/1467420487841448160.jpg',
    'goods_num' => 0,
    'level' => 1,
    'id' => '37',
    'name' => '手工DIY',
  ),
  36 => 
  array (
    'cat_id' => '36',
    'cat_name' => '消遣游戏',
    'measure_unit' => '本',
    'parent_id' => '26',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'category_img' => 'images/201607/1467420993452382708.jpg',
    'goods_num' => 0,
    'level' => 1,
    'id' => '36',
    'name' => '消遣游戏',
  ),
  35 => 
  array (
    'cat_id' => '35',
    'cat_name' => '偶像、明星',
    'measure_unit' => '本',
    'parent_id' => '26',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'category_img' => 'images/201607/1467421057126755514.jpg',
    'goods_num' => 0,
    'level' => 1,
    'id' => '35',
    'name' => '偶像、明星',
  ),
  23 => 
  array (
    'cat_id' => '23',
    'cat_name' => '考试',
    'measure_unit' => '本',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '8',
    'category_img' => NULL,
    'goods_num' => 0,
    'level' => 0,
    'id' => '23',
    'name' => '考试',
  ),
  27 => 
  array (
    'cat_id' => '27',
    'cat_name' => '小考',
    'measure_unit' => '本',
    'parent_id' => '23',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'category_img' => 'images/201607/1467421161361457491.jpg',
    'goods_num' => 0,
    'level' => 1,
    'id' => '27',
    'name' => '小考',
  ),
  33 => 
  array (
    'cat_id' => '33',
    'cat_name' => '自学考试',
    'measure_unit' => '本',
    'parent_id' => '23',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'category_img' => 'images/201607/1467421173959857914.jpg',
    'goods_num' => 0,
    'level' => 1,
    'id' => '33',
    'name' => '自学考试',
  ),
  32 => 
  array (
    'cat_id' => '32',
    'cat_name' => '成人高考',
    'measure_unit' => '本',
    'parent_id' => '23',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'category_img' => 'images/201607/1467421088657317038.jpg',
    'goods_num' => 0,
    'level' => 1,
    'id' => '32',
    'name' => '成人高考',
  ),
  31 => 
  array (
    'cat_id' => '31',
    'cat_name' => '研究生入学考试',
    'measure_unit' => '本',
    'parent_id' => '23',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'category_img' => 'images/201607/1467421110414064362.jpg',
    'goods_num' => 0,
    'level' => 1,
    'id' => '31',
    'name' => '研究生入学考试',
  ),
  30 => 
  array (
    'cat_id' => '30',
    'cat_name' => '高考',
    'measure_unit' => '本',
    'parent_id' => '23',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'category_img' => 'images/201607/1467421119447901041.jpg',
    'goods_num' => 0,
    'level' => 1,
    'id' => '30',
    'name' => '高考',
  ),
  29 => 
  array (
    'cat_id' => '29',
    'cat_name' => '中考',
    'measure_unit' => '本',
    'parent_id' => '23',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'category_img' => 'images/201607/1467421130535430715.jpg',
    'goods_num' => 0,
    'level' => 1,
    'id' => '29',
    'name' => '中考',
  ),
  28 => 
  array (
    'cat_id' => '28',
    'cat_name' => '会考',
    'measure_unit' => '本',
    'parent_id' => '23',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'category_img' => 'images/201607/1467421140522578742.jpg',
    'goods_num' => 0,
    'level' => 1,
    'id' => '28',
    'name' => '会考',
  ),
  34 => 
  array (
    'cat_id' => '34',
    'cat_name' => '公务员考试',
    'measure_unit' => '本',
    'parent_id' => '23',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'category_img' => 'images/201607/1467421151288793523.jpg',
    'goods_num' => 0,
    'level' => 1,
    'id' => '34',
    'name' => '公务员考试',
  ),
  20 => 
  array (
    'cat_id' => '20',
    'cat_name' => '艺术与摄影',
    'measure_unit' => '本',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '7',
    'category_img' => NULL,
    'goods_num' => 0,
    'level' => 0,
    'id' => '20',
    'name' => '艺术与摄影',
  ),
  40 => 
  array (
    'cat_id' => '40',
    'cat_name' => '绘画技法',
    'measure_unit' => '本',
    'parent_id' => '20',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'category_img' => 'images/201607/1467421258597170146.jpg',
    'goods_num' => 0,
    'level' => 1,
    'id' => '40',
    'name' => '绘画技法',
  ),
  46 => 
  array (
    'cat_id' => '46',
    'cat_name' => '人像摄影',
    'measure_unit' => '本',
    'parent_id' => '20',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'category_img' => 'images/201607/1467421265076225425.jpg',
    'goods_num' => 0,
    'level' => 1,
    'id' => '46',
    'name' => '人像摄影',
  ),
  45 => 
  array (
    'cat_id' => '45',
    'cat_name' => '摄影教程',
    'measure_unit' => '本',
    'parent_id' => '20',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'category_img' => 'images/201607/1467421184001644315.jpg',
    'goods_num' => 0,
    'level' => 1,
    'id' => '45',
    'name' => '摄影教程',
  ),
  44 => 
  array (
    'cat_id' => '44',
    'cat_name' => '硬笔字帖',
    'measure_unit' => '本',
    'parent_id' => '20',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'category_img' => 'images/201607/1467421219580356051.jpg',
    'goods_num' => 0,
    'level' => 1,
    'id' => '44',
    'name' => '硬笔字帖',
  ),
  43 => 
  array (
    'cat_id' => '43',
    'cat_name' => '名家作品',
    'measure_unit' => '本',
    'parent_id' => '20',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'category_img' => 'images/201607/1467421229206589811.jpg',
    'goods_num' => 0,
    'level' => 1,
    'id' => '43',
    'name' => '名家作品',
  ),
  42 => 
  array (
    'cat_id' => '42',
    'cat_name' => '书法教程',
    'measure_unit' => '本',
    'parent_id' => '20',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'category_img' => 'images/201607/1467421240778697826.jpg',
    'goods_num' => 0,
    'level' => 1,
    'id' => '42',
    'name' => '书法教程',
  ),
  41 => 
  array (
    'cat_id' => '41',
    'cat_name' => '素描速写',
    'measure_unit' => '本',
    'parent_id' => '20',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'category_img' => 'images/201607/1467421249183988489.jpg',
    'goods_num' => 0,
    'level' => 1,
    'id' => '41',
    'name' => '素描速写',
  ),
  25 => 
  array (
    'cat_id' => '25',
    'cat_name' => '时尚',
    'measure_unit' => '本',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '4',
    'has_children' => '0',
    'category_img' => NULL,
    'goods_num' => 0,
    'level' => 0,
    'id' => '25',
    'name' => '时尚',
  ),
  17 => 
  array (
    'cat_id' => '17',
    'cat_name' => '孕产育儿',
    'measure_unit' => '本',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '5',
    'has_children' => '0',
    'category_img' => NULL,
    'goods_num' => 0,
    'level' => 0,
    'id' => '17',
    'name' => '孕产育儿',
  ),
  19 => 
  array (
    'cat_id' => '19',
    'cat_name' => '文学',
    'measure_unit' => '本',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '6',
    'has_children' => '0',
    'category_img' => NULL,
    'goods_num' => 0,
    'level' => 0,
    'id' => '19',
    'name' => '文学',
  ),
  21 => 
  array (
    'cat_id' => '21',
    'cat_name' => '传记',
    'measure_unit' => '本',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '7',
    'has_children' => '0',
    'category_img' => NULL,
    'goods_num' => 0,
    'level' => 0,
    'id' => '21',
    'name' => '传记',
  ),
  22 => 
  array (
    'cat_id' => '22',
    'cat_name' => '励志与成功',
    'measure_unit' => '本',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '8',
    'has_children' => '0',
    'category_img' => NULL,
    'goods_num' => 0,
    'level' => 0,
    'id' => '22',
    'name' => '励志与成功',
  ),
  24 => 
  array (
    'cat_id' => '24',
    'cat_name' => '中小学教辅',
    'measure_unit' => '本',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '9',
    'has_children' => '0',
    'category_img' => NULL,
    'goods_num' => 0,
    'level' => 0,
    'id' => '24',
    'name' => '中小学教辅',
  ),
  16 => 
  array (
    'cat_id' => '16',
    'cat_name' => '小说',
    'measure_unit' => '本',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '10',
    'has_children' => '0',
    'category_img' => NULL,
    'goods_num' => 0,
    'level' => 0,
    'id' => '16',
    'name' => '小说',
  ),
  18 => 
  array (
    'cat_id' => '18',
    'cat_name' => '少儿',
    'measure_unit' => '本',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '11',
    'has_children' => '0',
    'category_img' => NULL,
    'goods_num' => 0,
    'level' => 0,
    'id' => '18',
    'name' => '少儿',
  ),
);
?>