<?php
$data = array (
  47 => 
  array (
    'cat_id' => '47',
    'cat_name' => '测试类别',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '1',
    'category_img' => '',
    'goods_num' => 0,
    'level' => 0,
    'id' => '47',
    'name' => '测试类别',
  ),
  48 => 
  array (
    'cat_id' => '48',
    'cat_name' => '测试类别',
    'measure_unit' => '',
    'parent_id' => '47',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '0',
    'category_img' => 'images/201607/1467609886765203673.jpg',
    'goods_num' => '11',
    'level' => 1,
    'id' => '48',
    'name' => '测试类别',
  ),
  50 => 
  array (
    'cat_id' => '50',
    'cat_name' => '小学/小升初',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '8',
    'category_img' => 'images/201607/1467943829587340510.jpg',
    'goods_num' => 0,
    'level' => 0,
    'id' => '50',
    'name' => '小学/小升初',
  ),
  51 => 
  array (
    'cat_id' => '51',
    'cat_name' => '1年级',
    'measure_unit' => '',
    'parent_id' => '50',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '4',
    'has_children' => '0',
    'category_img' => '',
    'goods_num' => 0,
    'level' => 1,
    'id' => '51',
    'name' => '1年级',
  ),
  52 => 
  array (
    'cat_id' => '52',
    'cat_name' => '2年级',
    'measure_unit' => '',
    'parent_id' => '50',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '5',
    'has_children' => '0',
    'category_img' => '',
    'goods_num' => 0,
    'level' => 1,
    'id' => '52',
    'name' => '2年级',
  ),
  54 => 
  array (
    'cat_id' => '54',
    'cat_name' => '3年级',
    'measure_unit' => '',
    'parent_id' => '50',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '6',
    'has_children' => '0',
    'category_img' => '',
    'goods_num' => 0,
    'level' => 1,
    'id' => '54',
    'name' => '3年级',
  ),
  55 => 
  array (
    'cat_id' => '55',
    'cat_name' => '4年级',
    'measure_unit' => '',
    'parent_id' => '50',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '7',
    'has_children' => '0',
    'category_img' => '',
    'goods_num' => 0,
    'level' => 1,
    'id' => '55',
    'name' => '4年级',
  ),
  56 => 
  array (
    'cat_id' => '56',
    'cat_name' => '5年级',
    'measure_unit' => '',
    'parent_id' => '50',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '8',
    'has_children' => '0',
    'category_img' => '',
    'goods_num' => 0,
    'level' => 1,
    'id' => '56',
    'name' => '5年级',
  ),
  57 => 
  array (
    'cat_id' => '57',
    'cat_name' => '6年级',
    'measure_unit' => '',
    'parent_id' => '50',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '9',
    'has_children' => '0',
    'category_img' => '',
    'goods_num' => 0,
    'level' => 1,
    'id' => '57',
    'name' => '6年级',
  ),
  58 => 
  array (
    'cat_id' => '58',
    'cat_name' => '小学升初中必备',
    'measure_unit' => '',
    'parent_id' => '50',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '10',
    'has_children' => '0',
    'category_img' => '',
    'goods_num' => 0,
    'level' => 1,
    'id' => '58',
    'name' => '小学升初中必备',
  ),
  59 => 
  array (
    'cat_id' => '59',
    'cat_name' => '小学工具书',
    'measure_unit' => '',
    'parent_id' => '50',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '11',
    'has_children' => '0',
    'category_img' => '',
    'goods_num' => 0,
    'level' => 1,
    'id' => '59',
    'name' => '小学工具书',
  ),
  60 => 
  array (
    'cat_id' => '60',
    'cat_name' => '初中/初升高',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '12',
    'has_children' => '4',
    'category_img' => 'images/201607/1467944085089177068.jpg',
    'goods_num' => 0,
    'level' => 0,
    'id' => '60',
    'name' => '初中/初升高',
  ),
  62 => 
  array (
    'cat_id' => '62',
    'cat_name' => '7年级',
    'measure_unit' => '',
    'parent_id' => '60',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '13',
    'has_children' => '0',
    'category_img' => '',
    'goods_num' => 0,
    'level' => 1,
    'id' => '62',
    'name' => '7年级',
  ),
  63 => 
  array (
    'cat_id' => '63',
    'cat_name' => '8年级',
    'measure_unit' => '',
    'parent_id' => '60',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '14',
    'has_children' => '0',
    'category_img' => '',
    'goods_num' => 0,
    'level' => 1,
    'id' => '63',
    'name' => '8年级',
  ),
  64 => 
  array (
    'cat_id' => '64',
    'cat_name' => '9年级',
    'measure_unit' => '',
    'parent_id' => '60',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '15',
    'has_children' => '0',
    'category_img' => '',
    'goods_num' => 0,
    'level' => 1,
    'id' => '64',
    'name' => '9年级',
  ),
  65 => 
  array (
    'cat_id' => '65',
    'cat_name' => '中级升高中必备',
    'measure_unit' => '',
    'parent_id' => '60',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '16',
    'has_children' => '0',
    'category_img' => '',
    'goods_num' => 0,
    'level' => 1,
    'id' => '65',
    'name' => '中级升高中必备',
  ),
  66 => 
  array (
    'cat_id' => '66',
    'cat_name' => '高中',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '17',
    'has_children' => '7',
    'category_img' => 'images/201607/1467944572741840225.jpg',
    'goods_num' => 0,
    'level' => 0,
    'id' => '66',
    'name' => '高中',
  ),
  67 => 
  array (
    'cat_id' => '67',
    'cat_name' => '语文',
    'measure_unit' => '',
    'parent_id' => '66',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '18',
    'has_children' => '0',
    'category_img' => '',
    'goods_num' => 0,
    'level' => 1,
    'id' => '67',
    'name' => '语文',
  ),
  69 => 
  array (
    'cat_id' => '69',
    'cat_name' => '英语',
    'measure_unit' => '',
    'parent_id' => '66',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '19',
    'has_children' => '0',
    'category_img' => '',
    'goods_num' => 0,
    'level' => 1,
    'id' => '69',
    'name' => '英语',
  ),
  68 => 
  array (
    'cat_id' => '68',
    'cat_name' => '数学',
    'measure_unit' => '',
    'parent_id' => '66',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '20',
    'has_children' => '0',
    'category_img' => '',
    'goods_num' => 0,
    'level' => 1,
    'id' => '68',
    'name' => '数学',
  ),
  70 => 
  array (
    'cat_id' => '70',
    'cat_name' => '生物',
    'measure_unit' => '',
    'parent_id' => '66',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '21',
    'has_children' => '0',
    'category_img' => '',
    'goods_num' => 0,
    'level' => 1,
    'id' => '70',
    'name' => '生物',
  ),
  71 => 
  array (
    'cat_id' => '71',
    'cat_name' => '化学',
    'measure_unit' => '',
    'parent_id' => '66',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '22',
    'has_children' => '0',
    'category_img' => '',
    'goods_num' => 0,
    'level' => 1,
    'id' => '71',
    'name' => '化学',
  ),
  72 => 
  array (
    'cat_id' => '72',
    'cat_name' => '政治',
    'measure_unit' => '',
    'parent_id' => '66',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '23',
    'has_children' => '0',
    'category_img' => '',
    'goods_num' => 0,
    'level' => 1,
    'id' => '72',
    'name' => '政治',
  ),
  73 => 
  array (
    'cat_id' => '73',
    'cat_name' => '历史',
    'measure_unit' => '',
    'parent_id' => '66',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '24',
    'has_children' => '0',
    'category_img' => '',
    'goods_num' => 0,
    'level' => 1,
    'id' => '73',
    'name' => '历史',
  ),
  74 => 
  array (
    'cat_id' => '74',
    'cat_name' => '高考类',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '25',
    'has_children' => '1',
    'category_img' => 'images/201607/1467944618612176147.jpg',
    'goods_num' => 0,
    'level' => 0,
    'id' => '74',
    'name' => '高考类',
  ),
  75 => 
  array (
    'cat_id' => '75',
    'cat_name' => '一轮复习',
    'measure_unit' => '',
    'parent_id' => '74',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '26',
    'has_children' => '0',
    'category_img' => '',
    'goods_num' => 0,
    'level' => 1,
    'id' => '75',
    'name' => '一轮复习',
  ),
  76 => 
  array (
    'cat_id' => '76',
    'cat_name' => '品牌系列图书',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '32',
    'has_children' => '0',
    'category_img' => '',
    'goods_num' => 0,
    'level' => 0,
    'id' => '76',
    'name' => '品牌系列图书',
  ),
  77 => 
  array (
    'cat_id' => '77',
    'cat_name' => '青春文学',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '40',
    'has_children' => '0',
    'category_img' => '',
    'goods_num' => 0,
    'level' => 0,
    'id' => '77',
    'name' => '青春文学',
  ),
);
?>